# Generated by Django 4.2.16 on 2024-10-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='titles',
            new_name='title',
        ),
    ]
